version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "adminadmin"
    ports:
      - "5432:5432"
    volumes:
      - db:/data/db
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres

volumes:
  db: