openapi: 3.0.0
/healthcheck:
  get:
    tags:
      - Sistema
    summary: Verifica a saúde do serviço
    description: Este endpoint pode ser utilizado para verificar se o servidor está disponível e acessível.
    responses:
      '200':
        description: Successful operation
        schema:
          type: string